;;; cc-consult-emoji.el --- summary -*- lexical-binding: t -*-

;; Author: Gabriele Lana <gabriele.lana@gmail.com>
;; Maintainer: Gabriele Lana <gabriele.lana@gmail.com>
;; Version: 0.0.1
;; Package-Requires: (_)
;; Homepage: http://github.com/gabrielelana/_
;; Keywords: _

;; This file is not part of GNU Emacs

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; For a full copy of the GNU General Public License
;; see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; _

;;; Code:

(require 'consult)

;; Comprehensive emoji list with (character name hex-code)
(defconst cc/consult--emoji-list
  '(
    ;; Smileys & Emotion
    ("😀" "grinning face" "U+1F600" "emotion happy smile positive cheerful")
    ("😃" "grinning face with big eyes" "U+1F603" "emotion happy excited smile cheerful")
    ("😄" "grinning face with smiling eyes" "U+1F604" "emotion happy smile eyes cheerful")
    ("😁" "beaming face with smiling eyes" "U+1F601" "emotion happy smile eyes proud")
    ("😆" "grinning squinting face" "U+1F606" "emotion happy laugh funny squint")
    ("😅" "grinning face with sweat" "U+1F605" "emotion nervous sweat relief awkward")
    ("🤣" "rolling on the floor laughing" "U+1F923" "emotion laugh funny hilarious rolling")
    ("😂" "face with tears of joy" "U+1F602" "emotion laugh funny tears joy")
    ("🙂" "slightly smiling face" "U+1F642" "emotion smile calm content neutral")
    ("🙃" "upside-down face" "U+1F643" "emotion silly playful sarcastic upside")
    ("😉" "winking face" "U+1F609" "emotion flirt wink playful cheeky")
    ("😊" "smiling face with smiling eyes" "U+1F60A" "emotion happy content smile eyes")
    ("😇" "smiling face with halo" "U+1F607" "emotion innocent angel good pure")
    ("🥰" "smiling face with hearts" "U+1F970" "emotion love hearts affection adorable")
    ("😍" "smiling face with heart-eyes" "U+1F60D" "emotion love hearts admire crush")
    ("🤩" "star-struck" "U+1F929" "emotion amazed star impressed wow")
    ("😘" "face blowing a kiss" "U+1F618" "emotion love kiss flirt affection")
    ("😗" "kissing face" "U+1F617" "emotion kiss affection love")
    ("😚" "kissing face with closed eyes" "U+1F61A" "emotion kiss affection love intimate")
    ("😙" "kissing face with smiling eyes" "U+1F619" "emotion kiss affection happy love")
    ("😋" "face savoring food" "U+1F60B" "emotion food delicious yummy taste")
    ("😛" "face with tongue" "U+1F61B" "emotion playful silly tongue cheeky")
    ("😜" "winking face with tongue" "U+1F61C" "emotion playful silly cheeky wink")
    ("🤪" "zany face" "U+1F92A" "emotion crazy silly wild goofy")
    ("😝" "squinting face with tongue" "U+1F61D" "emotion silly playful tongue cheeky")
    ("🤑" "money-mouth face" "U+1F911" "emotion money rich wealthy greedy")
    ("🤗" "hugging face" "U+1F917" "emotion hug comfort care affection")
    ("🤭" "face with hand over mouth" "U+1F92D" "emotion surprise shock gasp secret")
    ("🤫" "shushing face" "U+1F92B" "emotion quiet secret silence hush")
    ("🤔" "thinking face" "U+1F914" "emotion thinking ponder wonder confused")
    ("🤐" "zipper-mouth face" "U+1F910" "emotion quiet silent speechless secret")
    ("🤨" "face with raised eyebrow" "U+1F928" "emotion suspicious doubt skeptical")
    ("😐" "neutral face" "U+1F610" "emotion neutral blank expressionless")
    ("😑" "expressionless face" "U+1F611" "emotion neutral blank unimpressed")
    ("😶" "face without mouth" "U+1F636" "emotion silent speechless quiet neutral")
    ("😏" "smirking face" "U+1F60F" "emotion smug confident clever smirk")
    ("😒" "unamused face" "U+1F612" "emotion annoyed unimpressed disappointed")
    ("🙄" "face with rolling eyes" "U+1F644" "emotion annoyed sarcastic whatever")
    ("😬" "grimacing face" "U+1F62C" "emotion awkward nervous uncomfortable")
    ("🤥" "lying face" "U+1F925" "emotion lie dishonest pinocchio false")
    ("😌" "relieved face" "U+1F60C" "emotion relieved calm relaxed phew")
    ("😔" "pensive face" "U+1F614" "emotion sad thoughtful melancholy pensive")
    ("😪" "sleepy face" "U+1F62A" "emotion tired sleepy exhausted yawn")
    ("🤤" "drooling face" "U+1F924" "emotion drool hungry desire food")
    ("😴" "sleeping face" "U+1F634" "emotion sleep tired night zzz")
    ("😷" "face with medical mask" "U+1F637" "emotion sick mask doctor health")
    ("🤒" "face with thermometer" "U+1F912" "emotion sick fever ill temperature")
    ("🤕" "face with head-bandage" "U+1F915" "emotion hurt injured bandage accident")
    ("🤢" "nauseated face" "U+1F922" "emotion sick nauseous disgusted gross")
    ("🤮" "face vomiting" "U+1F92E" "emotion sick vomit nauseous disgusting")
    ("🤧" "sneezing face" "U+1F927" "emotion sick sneeze cold allergy")
    ("🥵" "hot face" "U+1F975" "emotion hot warm temperature fever")
    ("🥶" "cold face" "U+1F976" "emotion cold freezing temperature chill")
    ("🥴" "woozy face" "U+1F974" "emotion dizzy drunk confused wobbly")
    ("😵" "dizzy face" "U+1F635" "emotion dizzy confused overwhelmed cross-eyed")
    ("🤯" "exploding head" "U+1F92F" "emotion shocked amazed mindblown explosion")
    ("🤠" "cowboy hat face" "U+1F920" "emotion cowboy western hat yeehaw")
    ("🥳" "partying face" "U+1F973" "emotion party celebration fun hat")
    ("😎" "smiling face with sunglasses" "U+1F60E" "emotion cool sunglasses confident")
    ("🤓" "nerd face" "U+1F913" "emotion nerd glasses smart geek")
    ("🧐" "face with monocle" "U+1F9D0" "emotion monocle inspect curious sophisticated")
    ("😕" "confused face" "U+1F615" "emotion confused unsure uncertain")
    ("😟" "worried face" "U+1F61F" "emotion worried concerned anxious")
    ("🙁" "slightly frowning face" "U+1F641" "emotion sad disappointed unhappy")
    ("☹️" "frowning face" "U+2639" "emotion sad unhappy disappointed")
    ("😮" "face with open mouth" "U+1F62E" "emotion surprised shocked open")
    ("😯" "hushed face" "U+1F62F" "emotion surprised shocked quiet gasp")
    ("😲" "astonished face" "U+1F632" "emotion shocked amazed surprised wow")
    ("😳" "flushed face" "U+1F633" "emotion embarrassed shy blush red")
    ("🥺" "pleading face" "U+1F97A" "emotion pleading begging cute puppy")
    ("😦" "frowning face with open mouth" "U+1F626" "emotion shocked worried concerned")
    ("😧" "anguished face" "U+1F627" "emotion anguish pain stressed worried")
    ("😨" "fearful face" "U+1F628" "emotion scared afraid fear terror")
    ("😰" "anxious face with sweat" "U+1F630" "emotion anxious nervous sweat worried")
    ("😥" "sad but relieved face" "U+1F625" "emotion sad relief mixed emotions")
    ("😢" "crying face" "U+1F622" "emotion sad cry tears upset")
    ("😭" "loudly crying face" "U+1F62D" "emotion sad cry tears loud sob")
    ("😱" "face screaming in fear" "U+1F631" "emotion scared scream horror fear")
    ("😖" "confounded face" "U+1F616" "emotion frustrated confused upset")
    ("😣" "persevering face" "U+1F623" "emotion struggle effort determined")
    ("😞" "disappointed face" "U+1F61E" "emotion disappointed sad letdown")
    ("😓" "downcast face with sweat" "U+1F613" "emotion sad sweat anxious stressed")
    ("😩" "weary face" "U+1F629" "emotion tired exhausted weary drained")
    ("😫" "tired face" "U+1F62B" "emotion tired exhausted sleepy")
    ("🥱" "yawning face" "U+1F971" "emotion tired yawn sleepy bored")
    ("😤" "face with steam from nose" "U+1F624" "emotion angry frustrated steam triumph")
    ("😡" "pouting face" "U+1F621" "emotion angry mad furious upset")
    ("😠" "angry face" "U+1F620" "emotion angry mad upset annoyed")
    ("🤬" "face with symbols on mouth" "U+1F92C" "emotion angry curse swear symbols")
    ("😈" "smiling face with horns" "U+1F608" "emotion devil evil horns mischievous")
    ("👿" "angry face with horns" "U+1F47F" "emotion devil angry evil horns")
    ("💀" "skull" "U+1F480" "object death skull skeleton scary")
    ("☠️" "skull and crossbones" "U+2620" "object death poison danger pirate")
    ("💩" "pile of poo" "U+1F4A9" "object poop shit crap feces")
    ("🤡" "clown face" "U+1F921" "object clown circus funny scary")
    ("👹" "ogre" "U+1F479" "creature monster ogre demon scary")
    ("👺" "goblin" "U+1F47A" "creature goblin monster evil scary")
    ("👻" "ghost" "U+1F47B" "creature ghost spooky halloween scary")
    ("👽" "alien" "U+1F47D" "creature alien ufo space extraterrestrial")
    ("👾" "alien monster" "U+1F47E" "creature monster alien game pixel")
    ("🤖" "robot face" "U+1F916" "object robot machine technology ai")
    ("😺" "grinning cat face" "U+1F63A" "animal cat happy smile pet")
    ("😸" "grinning cat face with smiling eyes" "U+1F638" "animal cat happy smile eyes pet")
    ("😹" "cat face with tears of joy" "U+1F639" "animal cat laugh funny tears pet")
    ("😻" "smiling cat face with heart-eyes" "U+1F63B" "animal cat love hearts pet cute")
    ("😼" "cat face with wry smile" "U+1F63C" "animal cat smile clever pet")
    ("😽" "kissing cat face" "U+1F63D" "animal cat kiss affection pet")
    ("🙀" "weary cat face" "U+1F640" "animal cat scared shocked surprised pet")
    ("😿" "crying cat face" "U+1F63F" "animal cat sad tears upset pet")
    ("😾" "pouting cat face" "U+1F63E" "animal cat angry annoyed mad pet")

    ;; Gestures & Body Parts
    ("👋" "waving hand" "U+1F44B" "gesture wave hello goodbye hand")
    ("🤚" "raised back of hand" "U+1F91A" "gesture hand stop back")
    ("🖐️" "hand with fingers splayed" "U+1F590" "gesture hand fingers splayed open")
    ("✋" "raised hand" "U+270B" "gesture hand raise stop hello")
    ("🖖" "vulcan salute" "U+1F596" "gesture hand vulcan star trek spock")
    ("👌" "OK hand" "U+1F44C" "gesture hand ok perfect yes")
    ("🤌" "pinched fingers" "U+1F90C" "gesture hand fingers pinch italian")
    ("🤏" "pinching hand" "U+1F90F" "gesture hand fingers pinch small")
    ("✌️" "victory hand" "U+270C" "gesture hand victory peace two")
    ("🤞" "crossed fingers" "U+1F91E" "gesture hand fingers crossed luck")
    ("🤟" "love-you gesture" "U+1F91F" "gesture hand love sign language")
    ("🤘" "sign of the horns" "U+1F918" "gesture hand horns rock devil")
    ("🤙" "call me hand" "U+1F919" "gesture hand phone call")
    ("👈" "backhand index pointing left" "U+1F448" "gesture hand point left direction")
    ("👉" "backhand index pointing right" "U+1F449" "gesture hand point right direction")
    ("👆" "backhand index pointing up" "U+1F446" "gesture hand point up direction")
    ("🖕" "middle finger" "U+1F595" "gesture hand finger fuck offensive")
    ("👇" "backhand index pointing down" "U+1F447" "gesture hand point down direction")
    ("☝️" "index pointing up" "U+261D" "gesture hand point up direction one")
    ("👍" "thumbs up" "U+1F44D" "gesture hand thumb up yes good")
    ("👎" "thumbs down" "U+1F44E" "gesture hand thumb down no bad")
    ("✊" "raised fist" "U+270A" "gesture hand fist power solidarity")
    ("👊" "oncoming fist" "U+1F44A" "gesture hand fist punch bump")
    ("🤛" "left-facing fist" "U+1F91B" "gesture hand fist left bump")
    ("🤜" "right-facing fist" "U+1F91C" "gesture hand fist right bump")
    ("👏" "clapping hands" "U+1F44F" "gesture hands clap applause praise")
    ("🙌" "raising hands" "U+1F64C" "gesture hands raise celebrate praise")
    ("👐" "open hands" "U+1F450" "gesture hands open hug embrace")
    ("🤲" "palms up together" "U+1F932" "gesture hands palms up open")
    ("🤝" "handshake" "U+1F91D" "gesture hands shake agreement deal")
    ("🙏" "folded hands" "U+1F64F" "gesture hands fold pray please thanks")
    ("✍️" "writing hand" "U+270D" "gesture hand write sign signature")
    ("💅" "nail polish" "U+1F485" "beauty nail polish manicure hand")
    ("🤳" "selfie" "U+1F933" "gesture phone selfie picture camera")
    ("💪" "flexed biceps" "U+1F4AA" "body muscle strong fitness bicep")
    ("🦾" "mechanical arm" "U+1F9BE" "body arm mechanical robot cyborg")
    ("🦿" "mechanical leg" "U+1F9BF" "body leg mechanical robot cyborg")
    ("🦵" "leg" "U+1F9B5" "body leg foot limb")
    ("🦶" "foot" "U+1F9B6" "body foot leg toe")
    ("👂" "ear" "U+1F442" "body ear hearing listen sound")
    ("🦻" "ear with hearing aid" "U+1F9BB" "body ear hearing aid deaf")
    ("👃" "nose" "U+1F443" "body nose smell breathe")
    ("🧠" "brain" "U+1F9E0" "body brain mind think intelligence")
    ("🫀" "anatomical heart" "U+1FAC0" "body heart organ medical anatomy")
    ("🫁" "lungs" "U+1FAC1" "body lungs breathe organ medical")
    ("🦷" "tooth" "U+1F9B7" "body tooth dental mouth")
    ("🦴" "bone" "U+1F9B4" "body bone skeleton medical")
    ("👀" "eyes" "U+1F440" "body eyes look see watch")
    ("👁️" "eye" "U+1F441" "body eye look see watch")
    ("👅" "tongue" "U+1F445" "body tongue taste lick mouth")
    ("👄" "mouth" "U+1F444" "body mouth speak eat kiss")
    ("🫦" "lips" "U+1FAE6" "body lips mouth kiss speak")

    ;; People & Body
    ("👶" "baby" "U+1F476" "person baby infant child young")
    ("🧒" "child" "U+1F9D2" "person child kid young")
    ("👦" "boy" "U+1F466" "person boy male child kid")
    ("👧" "girl" "U+1F467" "person girl female child kid")
    ("🧑" "person" "U+1F9D1" "person human individual adult")
    ("👱" "person with blond hair" "U+1F471" "person blond hair yellow")
    ("👨" "man" "U+1F468" "person man male adult")
    ("🧔" "man with beard" "U+1F9D4" "person man beard facial hair")
    ("👩" "woman" "U+1F469" "person woman female adult")
    ("🧓" "older person" "U+1F9D3" "person old elderly senior")
    ("👴" "old man" "U+1F474" "person old man elderly senior")
    ("👵" "old woman" "U+1F475" "person old woman elderly senior")
    ("🙍" "frowning person" "U+1F64D" "person frown sad disappointed")
    ("🙎" "pouting person" "U+1F64E" "person pout angry annoyed")
    ("🙅" "person gesturing no" "U+1F645" "person gesture no refuse deny")
    ("🙆" "person gesturing OK" "U+1F646" "person gesture ok yes agree")
    ("💁" "person tipping hand" "U+1F481" "person gesture help information")
    ("🙋" "person raising hand" "U+1F64B" "person gesture raise volunteer question")
    ("🧏" "deaf person" "U+1F9CF" "person deaf hearing impaired sign")
    ("🙇" "person bowing" "U+1F647" "person bow respect sorry thank")
    ("🤦" "face palm" "U+1F926" "person gesture facepalm disappointed")
    ("🤷" "shrugging person" "U+1F937" "person gesture shrug unsure")
    ("🧑‍⚕️" "health worker" "U+1F91D" "profession doctor nurse medical health")
    ("👨‍⚕️" "man health worker" "U+1F468" "profession doctor man medical")
    ("👩‍⚕️" "woman health worker" "U+1F469" "profession doctor woman medical")
    ("🧑‍🎓" "student" "U+1F9D1" "profession student school graduate")
    ("👨‍🎓" "man student" "U+1F468" "profession student man school")
    ("👩‍🎓" "woman student" "U+1F469" "profession student woman school")
    ("🧑‍🏫" "teacher" "U+1F9D1" "profession teacher school education")
    ("👨‍🏫" "man teacher" "U+1F468" "profession teacher man school")
    ("👩‍🏫" "woman teacher" "U+1F469" "profession teacher woman school")
    ("🧑‍⚖️" "judge" "U+1F9D1" "profession judge law court legal")
    ("👨‍⚖️" "man judge" "U+1F468" "profession judge man law")
    ("👩‍⚖️" "woman judge" "U+1F469" "profession judge woman law")
    ("🧑‍🌾" "farmer" "U+1F9D1" "profession farmer agriculture farm")
    ("👨‍🌾" "man farmer" "U+1F468" "profession farmer man agriculture")
    ("👩‍🌾" "woman farmer" "U+1F469" "profession farmer woman agriculture")
    ("🧑‍🍳" "cook" "U+1F9D1" "profession cook chef food kitchen")
    ("👨‍🍳" "man cook" "U+1F468" "profession cook man chef")
    ("👩‍🍳" "woman cook" "U+1F469" "profession cook woman chef")
    ("🧑‍🔧" "mechanic" "U+1F9D1" "profession mechanic repair tools")
    ("👨‍🔧" "man mechanic" "U+1F468" "profession mechanic man repair")
    ("👩‍🔧" "woman mechanic" "U+1F469" "profession mechanic woman repair")
    ("🧑‍🏭" "factory worker" "U+1F9D1" "profession factory worker industry")
    ("👨‍🏭" "man factory worker" "U+1F468" "profession factory man worker")
    ("👩‍🏭" "woman factory worker" "U+1F469" "profession factory woman worker")
    ("🧑‍💼" "office worker" "U+1F9D1" "profession office worker business")
    ("👨‍💼" "man office worker" "U+1F468" "profession office man business")
    ("👩‍💼" "woman office worker" "U+1F469" "profession office woman business")
    ("🧑‍🔬" "scientist" "U+1F9D1" "profession scientist research lab")
    ("👨‍🔬" "man scientist" "U+1F468" "profession scientist man research")
    ("👩‍🔬" "woman scientist" "U+1F469" "profession scientist woman research")
    ("🧑‍💻" "technologist" "U+1F9D1" "profession technologist computer tech")
    ("👨‍💻" "man technologist" "U+1F468" "profession technologist man computer")
    ("👩‍💻" "woman technologist" "U+1F469" "profession technologist woman computer")
    ("🧑‍🎤" "singer" "U+1F9D1" "profession singer music performer")
    ("👨‍🎤" "man singer" "U+1F468" "profession singer man music")
    ("👩‍🎤" "woman singer" "U+1F469" "profession singer woman music")
    ("🧑‍🎨" "artist" "U+1F9D1" "profession artist paint creative")
    ("👨‍🎨" "man artist" "U+1F468" "profession artist man paint")
    ("👩‍🎨" "woman artist" "U+1F469" "profession artist woman paint")
    ("🧑‍✈️" "pilot" "U+1F9D1" "profession pilot airplane flight")
    ("👨‍✈️" "man pilot" "U+1F468" "profession pilot man airplane")
    ("👩‍✈️" "woman pilot" "U+1F469" "profession pilot woman airplane")
    ("🧑‍🚀" "astronaut" "U+1F9D1" "profession astronaut space rocket")
    ("👨‍🚀" "man astronaut" "U+1F468" "profession astronaut man space")
    ("👩‍🚀" "woman astronaut" "U+1F469" "profession astronaut woman space")
    ("🧑‍🚒" "firefighter" "U+1F9D1" "profession firefighter fire emergency")
    ("👨‍🚒" "man firefighter" "U+1F468" "profession firefighter man fire")
    ("👩‍🚒" "woman firefighter" "U+1F469" "profession firefighter woman fire")
    ("👮" "police officer" "U+1F46E" "profession police officer law")
    ("🕵️" "detective" "U+1F575" "profession detective spy mystery")
    ("💂" "guard" "U+1F482" "profession guard security soldier")
    ("🥷" "ninja" "U+1F977" "profession ninja warrior stealth")
    ("👷" "construction worker" "U+1F477" "profession construction worker builder")
    ("🫵" "index pointing at viewer" "U+1FAF5" "gesture hand point you viewer")
    ("🫶" "heart hands" "U+1FAF6" "gesture hands heart love care")
    ("🫸" "rightwards hand" "U+1FAF8" "gesture hand right direction")
    ("🫷" "leftwards hand" "U+1FAF9" "gesture hand left direction")
    ("🫹" "palm down hand" "U+1FAFA" "gesture hand palm down stop")
    ("🫺" "palm up hand" "U+1FAFB" "gesture hand palm up give")
    ("🫻" "leftwards pushing hand" "U+1FAFC" "gesture hand push left")
    ("🫼" "rightwards pushing hand" "U+1FAFD" "gesture hand push right")

    ;; Animals & Nature
    ("🐶" "dog face" "U+1F436" "animal dog pet puppy canine")
    ("🐱" "cat face" "U+1F431" "animal cat pet kitten feline")
    ("🐭" "mouse face" "U+1F42D" "animal mouse rodent pet small")
    ("🐹" "hamster face" "U+1F439" "animal hamster pet rodent cute")
    ("🐰" "rabbit face" "U+1F430" "animal rabbit pet bunny cute")
    ("🦊" "fox face" "U+1F98A" "animal fox wild canine clever")
    ("🐻" "bear face" "U+1F43B" "animal bear wild strong")
    ("🐼" "panda face" "U+1F43C" "animal panda bear cute china")
    ("🐻‍❄️" "polar bear" "U+1F43B" "animal bear polar white arctic")
    ("🐨" "koala" "U+1F428" "animal koala bear cute australia")
    ("🐯" "tiger face" "U+1F42F" "animal tiger wild striped cat")
    ("🦁" "lion face" "U+1F981" "animal lion wild king cat")
    ("🐮" "cow face" "U+1F42E" "animal cow farm cattle milk")
    ("🐷" "pig face" "U+1F437" "animal pig farm pork cute")
    ("🐽" "pig nose" "U+1F43D" "animal pig nose snout")
    ("🐸" "frog face" "U+1F438" "animal frog amphibian green hop")
    ("🐵" "monkey face" "U+1F435" "animal monkey primate banana")
    ("🙈" "see-no-evil monkey" "U+1F648" "animal monkey evil see cover")
    ("🙉" "hear-no-evil monkey" "U+1F649" "animal monkey evil hear cover")
    ("🙊" "speak-no-evil monkey" "U+1F64A" "animal monkey evil speak cover")
    ("🐒" "monkey" "U+1F412" "animal monkey primate wild")
    ("🐔" "chicken" "U+1F414" "animal chicken bird farm egg")
    ("🐧" "penguin" "U+1F427" "animal penguin bird antarctic")
    ("🐦" "bird" "U+1F426" "animal bird fly tweet nature")
    ("🐦‍⬛" "black bird" "U+1F426" "animal bird black crow")
    ("🐤" "baby chick" "U+1F424" "animal bird chick cute yellow")
    ("🐣" "hatching chick" "U+1F423" "animal bird chick hatch egg")
    ("🐥" "front-facing baby chick" "U+1F425" "animal bird chick cute")
    ("🦆" "duck" "U+1F986" "animal duck bird water quack")
    ("🦅" "eagle" "U+1F985" "animal eagle bird predator majestic")
    ("🦉" "owl" "U+1F989" "animal owl bird night wise")
    ("🦇" "bat" "U+1F987" "animal bat night fly vampire")
    ("🐺" "wolf" "U+1F43A" "animal wolf wild howl pack")
    ("🐗" "boar" "U+1F417" "animal boar pig wild hunt")
    ("🐴" "horse face" "U+1F434" "animal horse ride gallop farm")
    ("🦄" "unicorn" "U+1F984" "animal unicorn horse magical rainbow")
    ("🐝" "honeybee" "U+1F41D" "animal bee insect honey sting")
    ("🐛" "bug" "U+1F41B" "animal bug insect caterpillar")
    ("🦋" "butterfly" "U+1F98B" "animal butterfly insect beautiful")
    ("🐌" "snail" "U+1F40C" "animal snail slow shell slug")
    ("🐞" "lady beetle" "U+1F41E" "animal beetle insect ladybug red")
    ("🐜" "ant" "U+1F41C" "animal ant insect colony small")
    ("🦟" "mosquito" "U+1F99F" "animal mosquito insect bite disease")
    ("🦗" "cricket" "U+1F997" "animal cricket insect chirp jump")
    ("🕷️" "spider" "U+1F577" "animal spider insect web scary")
    ("🕸️" "spider web" "U+1F578" "object spider web insect trap")
    ("🦂" "scorpion" "U+1F982" "animal scorpion insect sting desert")
    ("🦠" "microbe" "U+1F9A0" "animal microbe virus bacteria germ")
    ("💐" "bouquet" "U+1F490" "plant flower bouquet gift beautiful")
    ("🌸" "cherry blossom" "U+1F338" "plant flower blossom cherry pink")
    ("💮" "white flower" "U+1F4AE" "plant flower white beautiful")
    ("🏵️" "rosette" "U+1F3F5" "plant flower rosette award decoration")
    ("🌹" "rose" "U+1F339" "plant flower rose red love romance")
    ("🥀" "wilted flower" "U+1F940" "plant flower wilted dead sad")
    ("🌺" "hibiscus" "U+1F33A" "plant flower hibiscus tropical pink")
    ("🌻" "sunflower" "U+1F33B" "plant flower sunflower yellow tall")
    ("🌼" "blossom" "U+1F33C" "plant flower blossom spring yellow")
    ("🌷" "tulip" "U+1F337" "plant flower tulip spring colorful")
    ("🌱" "seedling" "U+1F331" "plant seedling grow young green")
    ("🪴" "potted plant" "U+1FAB4" "plant potted houseplant indoor green")
    ("🌲" "evergreen tree" "U+1F332" "plant tree evergreen pine forest")
    ("🌳" "deciduous tree" "U+1F333" "plant tree deciduous forest nature")
    ("🌴" "palm tree" "U+1F334" "plant tree palm tropical beach")
    ("🌵" "cactus" "U+1F335" "plant cactus desert spike succulent")
    ("🌾" "sheaf of rice" "U+1F33E" "plant rice grain harvest agriculture")
    ("🌿" "herb" "U+1F33F" "plant herb green leaf nature")
    ("☘️" "shamrock" "U+2618" "plant shamrock clover ireland luck")
    ("🍀" "four leaf clover" "U+1F340" "plant clover four leaf luck")
    ("🍁" "maple leaf" "U+1F341" "plant leaf maple autumn canada")
    ("🍂" "fallen leaf" "U+1F342" "plant leaf fallen autumn nature")
    ("🍃" "leaf fluttering in wind" "U+1F343" "plant leaf wind nature green")

    ;; Food & Drink
    ("🍇" "grapes" "U+1F347" "food fruit grapes purple wine")
    ("🍈" "melon" "U+1F348" "food fruit melon green sweet")
    ("🍉" "watermelon" "U+1F349" "food fruit watermelon red summer")
    ("🍊" "tangerine" "U+1F34A" "food fruit tangerine orange citrus")
    ("🍋" "lemon" "U+1F34B" "food fruit lemon yellow citrus sour")
    ("🍌" "banana" "U+1F34C" "food fruit banana yellow potassium")
    ("🍍" "pineapple" "U+1F34D" "food fruit pineapple tropical sweet")
    ("🥭" "mango" "U+1F96D" "food fruit mango tropical sweet")
    ("🍎" "red apple" "U+1F34E" "food fruit apple red healthy")
    ("🍏" "green apple" "U+1F34F" "food fruit apple green sour")
    ("🍐" "pear" "U+1F350" "food fruit pear green sweet")
    ("🍑" "peach" "U+1F351" "food fruit peach pink fuzzy sweet")
    ("🍒" "cherries" "U+1F352" "food fruit cherries red sweet pair")
    ("🍓" "strawberry" "U+1F353" "food fruit strawberry red sweet")
    ("🫐" "blueberries" "U+1FAD0" "food fruit blueberries blue healthy")
    ("🥝" "kiwi fruit" "U+1F95D" "food fruit kiwi green fuzzy")
    ("🍅" "tomato" "U+1F345" "food vegetable tomato red fruit")
    ("🫒" "olive" "U+1FACE" "food olive green oil mediterranean")
    ("🥥" "coconut" "U+1F965" "food fruit coconut tropical milk")
    ("🥑" "avocado" "U+1F951" "food fruit avocado green healthy")
    ("🍆" "eggplant" "U+1F346" "food vegetable eggplant purple")
    ("🥔" "potato" "U+1F954" "food vegetable potato starch fry")
    ("🥕" "carrot" "U+1F955" "food vegetable carrot orange healthy")
    ("🌽" "corn" "U+1F33D" "food vegetable corn yellow maize")
    ("🌶️" "hot pepper" "U+1F336" "food vegetable pepper hot spicy")
    ("🫑" "bell pepper" "U+1FAD1" "food vegetable pepper colorful")
    ("🥒" "cucumber" "U+1F952" "food vegetable cucumber green fresh")
    ("🥬" "leafy green" "U+1F96C" "food vegetable green healthy salad")
    ("🥦" "broccoli" "U+1F966" "food vegetable broccoli green healthy")
    ("🧄" "garlic" "U+1F9C4" "food vegetable garlic flavor spice")
    ("🧅" "onion" "U+1F9C5" "food vegetable onion cry flavor")
    ("🍄" "mushroom" "U+1F344" "food fungus mushroom magic")
    ("🥜" "peanuts" "U+1F95C" "food nut peanut butter allergy")
    ("🌰" "chestnut" "U+1F330" "food nut chestnut roast winter")
    ("🍞" "bread" "U+1F35E" "food bread wheat toast sandwich")
    ("🥐" "croissant" "U+1F950" "food bread croissant french buttery")
    ("🥖" "baguette bread" "U+1F956" "food bread baguette french long")
    ("🫓" "flatbread" "U+1FAD3" "food bread flatbread wrap")
    ("🥨" "pretzel" "U+1F968" "food bread pretzel salty german")
    ("🥯" "bagel" "U+1F96F" "food bread bagel cream cheese")
    ("🥞" "pancakes" "U+1F95E" "food breakfast pancakes syrup sweet")
    ("🧇" "waffle" "U+1F9C7" "food breakfast waffle syrup belgian")
    ("🧀" "cheese wedge" "U+1F9C0" "food cheese dairy yellow")
    ("🍖" "meat on bone" "U+1F356" "food meat bone barbecue")
    ("🍗" "poultry leg" "U+1F357" "food meat chicken leg fried")
    ("🥩" "cut of meat" "U+1F969" "food meat steak beef")
    ("🥓" "bacon" "U+1F953" "food meat bacon pork breakfast")
    ("🍔" "hamburger" "U+1F354" "food hamburger burger beef fast")
    ("🍟" "french fries" "U+1F35F" "food fries potato fast salty")
    ("🍕" "pizza" "U+1F355" "food pizza cheese italian")
    ("🌭" "hot dog" "U+1F32D" "food hot dog sausage fast")
    ("🥪" "sandwich" "U+1F96A" "food sandwich bread lunch")
    ("🌮" "taco" "U+1F32E" "food taco mexican spicy")
    ("🌯" "burrito" "U+1F32F" "food burrito mexican wrap")
    ("🫔" "tamale" "U+1FAD4" "food tamale mexican corn")
    ("🥙" "stuffed flatbread" "U+1F959" "food wrap mediterranean gyro")
    ("🧆" "falafel" "U+1F9C6" "food falafel middle eastern vegetarian")
    ("🥚" "egg" "U+1F95A" "food egg breakfast protein")
    ("🍳" "cooking" "U+1F373" "food cooking egg breakfast pan")
    ("🥘" "shallow pan of food" "U+1F958" "food paella spanish rice")
    ("🍲" "pot of food" "U+1F372" "food stew soup hot meal")
    ("🫕" "fondue" "U+1FAD5" "food fondue cheese swiss")
    ("🥣" "bowl with spoon" "U+1F963" "food bowl cereal soup breakfast")
    ("🥗" "green salad" "U+1F957" "food salad healthy vegetarian")
    ("🍿" "popcorn" "U+1F37F" "food popcorn movie snack")
    ("🧈" "butter" "U+1F9C8" "food butter dairy yellow spread")
    ("🧂" "salt" "U+1F9C2" "food salt seasoning spice")
    ("🥫" "canned food" "U+1F96B" "food canned preserved storage")
    ("🍱" "bento box" "U+1F371" "food bento japanese lunch box")
    ("🍘" "rice cracker" "U+1F358" "food cracker rice japanese snack")
    ("🍙" "rice ball" "U+1F359" "food rice ball japanese onigiri")
    ("🍚" "cooked rice" "U+1F35A" "food rice cooked asian staple")
    ("🍛" "curry rice" "U+1F35B" "food curry rice indian spicy")
    ("🍜" "steaming bowl" "U+1F35C" "food soup noodles ramen asian")
    ("🍝" "spaghetti" "U+1F35D" "food pasta spaghetti italian")
    ("🍠" "roasted sweet potato" "U+1F360" "food sweet potato roasted vegetable")
    ("🍢" "oden" "U+1F362" "food oden japanese fish cake")
    ("🍣" "sushi" "U+1F363" "food sushi japanese fish rice")
    ("🍤" "fried shrimp" "U+1F364" "food shrimp fried seafood")
    ("🍥" "fish cake with swirl" "U+1F365" "food fish cake japanese pink")
    ("🥮" "moon cake" "U+1F96E" "food moon cake chinese festival")
    ("🍡" "dango" "U+1F361" "food dango japanese sweet skewer")
    ("🥟" "dumpling" "U+1F95F" "food dumpling chinese asian")
    ("🥠" "fortune cookie" "U+1F960" "food fortune cookie chinese dessert")
    ("🥡" "takeout box" "U+1F961" "food takeout chinese box container")
    ("🦀" "crab" "U+1F980" "food seafood crab shellfish")
    ("🦞" "lobster" "U+1F99E" "food seafood lobster shellfish luxury")
    ("🦐" "shrimp" "U+1F990" "food seafood shrimp shellfish")
    ("🦑" "squid" "U+1F991" "food seafood squid calamari")
    ("🦪" "oyster" "U+1F9AA" "food seafood oyster shellfish pearl")
    ("🍦" "soft ice cream" "U+1F366" "food dessert ice cream sweet cold")
    ("🍧" "shaved ice" "U+1F367" "food dessert shaved ice sweet cold")
    ("🍨" "ice cream" "U+1F368" "food dessert ice cream sweet")
    ("🍩" "doughnut" "U+1F369" "food dessert doughnut sweet breakfast")
    ("🍪" "cookie" "U+1F36A" "food dessert cookie sweet chocolate")
    ("🎂" "birthday cake" "U+1F382" "food dessert cake birthday celebration")
    ("🍰" "shortcake" "U+1F370" "food dessert cake strawberry sweet")
    ("🧁" "cupcake" "U+1F9C1" "food dessert cupcake sweet frosting")
    ("🥧" "pie" "U+1F967" "food dessert pie sweet apple")
    ("🍫" "chocolate bar" "U+1F36B" "food dessert chocolate sweet candy")
    ("🍬" "candy" "U+1F36C" "food dessert candy sweet sugar")
    ("🍭" "lollipop" "U+1F36D" "food dessert lollipop sweet candy")
    ("🍮" "custard" "U+1F36E" "food dessert custard sweet pudding")
    ("🍯" "honey pot" "U+1F36F" "food honey sweet bee natural")
    ("🍼" "baby bottle" "U+1F37C" "food baby bottle milk formula")
    ("🥛" "glass of milk" "U+1F95B" "food drink milk dairy calcium")
    ("☕" "hot beverage" "U+2615" "drink coffee hot caffeine morning")
    ("🫖" "teapot" "U+1FAD6" "drink teapot tea hot ceramic")
    ("🍵" "teacup without handle" "U+1F375" "drink tea hot green asian")
    ("🍶" "sake" "U+1F376" "drink sake alcohol japanese rice")
    ("🍾" "bottle with popping cork" "U+1F37E" "drink champagne celebration alcohol")
    ("🍷" "wine glass" "U+1F377" "drink wine alcohol red")
    ("🍸" "cocktail glass" "U+1F378" "drink cocktail alcohol party")
    ("🍹" "tropical drink" "U+1F379" "drink tropical cocktail vacation")
    ("🍺" "beer mug" "U+1F37A" "drink beer alcohol mug")
    ("🍻" "clinking beer mugs" "U+1F37B" "drink beer celebration alcohol")
    ("🥂" "clinking glasses" "U+1F942" "drink celebration toast alcohol")
    ("🥃" "tumbler glass" "U+1F943" "drink whiskey alcohol glass")
    ("🥤" "cup with straw" "U+1F964" "drink smoothie juice straw cold")
    ("🧋" "bubble tea" "U+1F9CB" "drink bubble tea tapioca asian")
    ("🧃" "beverage box" "U+1F9C3" "drink juice box straw")
    ("🧉" "mate" "U+1F9C9" "drink mate tea south american")
    ("🧊" "ice cube" "U+1F9CA" "object ice cube cold drink")

    ;; Travel & Places
    ("🌍" "globe showing Europe-Africa" "U+1F30D" "place globe earth world europe africa")
    ("🌎" "globe showing Americas" "U+1F30E" "place globe earth world americas")
    ("🌏" "globe showing Asia-Australia" "U+1F30F" "place globe earth world asia australia")
    ("🌐" "globe with meridians" "U+1F310" "place globe earth world internet")
    ("🗺️" "world map" "U+1F5FA" "place map world geography travel")
    ("🗾" "map of Japan" "U+1F5FE" "place map japan geography asia")
    ("🧭" "compass" "U+1F9ED" "object compass navigation direction travel")
    ("🏔️" "snow-capped mountain" "U+1F3D4" "place mountain snow cold high")
    ("⛰️" "mountain" "U+26F0" "place mountain nature hiking high")
    ("🌋" "volcano" "U+1F30B" "place volcano eruption lava dangerous")
    ("🗻" "mount fuji" "U+1F5FB" "place mountain fuji japan iconic")
    ("🏕️" "camping" "U+1F3D5" "place camping tent nature outdoor")
    ("🏖️" "beach with umbrella" "U+1F3D6" "place beach umbrella vacation summer")
    ("🏜️" "desert" "U+1F3DC" "place desert sand dry hot")
    ("🏝️" "desert island" "U+1F3DD" "place island desert tropical vacation")
    ("🏞️" "national park" "U+1F3DE" "place park nature protected scenic")
    ("🏟️" "stadium" "U+1F3DF" "place stadium sports event crowd")
    ("🏛️" "classical building" "U+1F3DB" "place building classical architecture greek")
    ("🏗️" "building construction" "U+1F3D7" "place building construction crane work")
    ("🧱" "brick" "U+1F9F1" "object brick construction building material")
    ("🪨" "rock" "U+1FAA8" "object rock stone nature geology")
    ("🪵" "wood" "U+1FAB5" "object wood tree material nature")
    ("🛖" "hut" "U+1F6D6" "place hut house simple rustic")
    ("🏘️" "houses" "U+1F3D8" "place houses neighborhood residential")
    ("🏚️" "derelict house" "U+1F3DA" "place house derelict abandoned old")
    ("🏠" "house" "U+1F3E0" "place house home residential")
    ("🏡" "house with garden" "U+1F3E1" "place house garden home residential")
    ("🏢" "office building" "U+1F3E2" "place building office work business")
    ("🏣" "post office" "U+1F3E3" "place post office mail government")
    ("🏤" "european post office" "U+1F3E4" "place post office mail european")
    ("🏥" "hospital" "U+1F3E5" "place hospital medical health emergency")
    ("🏦" "bank" "U+1F3E6" "place bank money finance business")
    ("🏨" "hotel" "U+1F3E8" "place hotel accommodation travel lodging")
    ("🏩" "love hotel" "U+1F3E9" "place hotel love romantic adult")
    ("🏪" "convenience store" "U+1F3EA" "place store convenience shop 247")
    ("🏫" "school" "U+1F3EB" "place school education learning students")
    ("🏬" "department store" "U+1F3EC" "place store department shopping mall")
    ("🏭" "factory" "U+1F3ED" "place factory industry manufacturing work")
    ("🏯" "japanese castle" "U+1F3EF" "place castle japanese historic asia")
    ("🏰" "castle" "U+1F3F0" "place castle historic medieval europe")
    ("💒" "wedding" "U+1F492" "place wedding chapel marriage ceremony")
    ("🗼" "tokyo tower" "U+1F5FC" "place tower tokyo japan landmark")
    ("🗽" "statue of liberty" "U+1F5FD" "place statue liberty new york landmark")
    ("⛪" "church" "U+26EA" "place church religion worship christian")
    ("🕌" "mosque" "U+1F54C" "place mosque religion worship islam")
    ("🛕" "hindu temple" "U+1F6D5" "place temple religion worship hindu")
    ("🕍" "synagogue" "U+1F54D" "place synagogue religion worship jewish")
    ("⛩️" "shinto shrine" "U+26E9" "place shrine religion shinto japan")
    ("🕋" "kaaba" "U+1F54B" "place kaaba mecca islam pilgrimage")
    ("⛲" "fountain" "U+26F2" "place fountain water park decorative")
    ("⛺" "tent" "U+26FA" "place tent camping outdoor shelter")
    ("🌁" "foggy" "U+1F301" "weather fog mist cloudy visibility")
    ("🌃" "night with stars" "U+1F303" "time night stars city urban")
    ("🏙️" "cityscape" "U+1F3D9" "place cityscape urban skyline buildings")
    ("🌄" "sunrise over mountains" "U+1F304" "time sunrise morning nature mountains")
    ("🌅" "sunrise" "U+1F305" "time sunrise morning dawn new")
    ("🌆" "cityscape at dusk" "U+1F306" "time dusk sunset city evening")
    ("🌇" "sunset" "U+1F307" "time sunset evening golden hour")
    ("🌉" "bridge at night" "U+1F309" "place bridge night city lights")
    ("♨️" "hot springs" "U+2668" "place hot springs spa water steam")
    ("🎠" "carousel horse" "U+1F3A0" "activity carousel carnival amusement ride")
    ("🎡" "ferris wheel" "U+1F3A1" "activity ferris wheel carnival amusement")
    ("🎢" "roller coaster" "U+1F3A2" "activity roller coaster thrill amusement")
    ("💈" "barber pole" "U+1F488" "place barber shop hair cut salon")
    ("🎪" "circus tent" "U+1F3AA" "place circus tent entertainment show")
    ("🚂" "steam locomotive" "U+1F682" "transport train steam locomotive railway")
    ("🚃" "railway car" "U+1F683" "transport train railway car passenger")
    ("🚄" "high-speed train" "U+1F684" "transport train high-speed railway fast")
    ("🚅" "bullet train" "U+1F685" "transport train bullet japan fast")
    ("🚆" "train" "U+1F686" "transport train railway passenger")
    ("🚇" "metro" "U+1F687" "transport metro subway underground city")
    ("🚈" "light rail" "U+1F688" "transport train light rail tram")
    ("🚉" "station" "U+1F689" "place station transport railway")
    ("🚊" "tram" "U+1F68A" "transport tram streetcar railway")
    ("🚝" "monorail" "U+1F69D" "transport monorail train railway single")
    ("🚞" "mountain railway" "U+1F69E" "transport train mountain railway scenic")
    ("🚋" "tram car" "U+1F68B" "transport tram streetcar passenger")
    ("🚌" "bus" "U+1F68C" "transport bus public passenger road")
    ("🚍" "oncoming bus" "U+1F68D" "transport bus oncoming passenger")
    ("🚎" "trolleybus" "U+1F68E" "transport trolleybus electric passenger")
    ("🚐" "minibus" "U+1F690" "transport minibus van passenger small")
    ("🚑" "ambulance" "U+1F691" "transport ambulance emergency medical")
    ("🚒" "fire engine" "U+1F692" "transport fire engine emergency truck")
    ("🚓" "police car" "U+1F693" "transport police car emergency law")
    ("🚔" "oncoming police car" "U+1F694" "transport police car oncoming emergency")
    ("🚕" "taxi" "U+1F695" "transport taxi cab yellow passenger")
    ("🚖" "oncoming taxi" "U+1F696" "transport taxi oncoming cab passenger")
    ("🚗" "automobile" "U+1F697" "transport car automobile vehicle")
    ("🚘" "oncoming automobile" "U+1F698" "transport car oncoming automobile")
    ("🚙" "sport utility vehicle" "U+1F699" "transport suv vehicle offroad")
    ("🛻" "pickup truck" "U+1F6FB" "transport truck pickup utility vehicle")
    ("🚚" "delivery truck" "U+1F69A" "transport truck delivery cargo")
    ("🚛" "articulated lorry" "U+1F69B" "transport truck lorry semi cargo")
    ("🚜" "tractor" "U+1F69C" "transport tractor farm agriculture vehicle")
    ("🏎️" "racing car" "U+1F3CE" "transport racing car sport fast")
    ("🏍️" "motorcycle" "U+1F3CD" "transport motorcycle bike vehicle")
    ("🛵" "motor scooter" "U+1F6F5" "transport scooter motorcycle vehicle")
    ("🦽" "manual wheelchair" "U+1F9BD" "transport wheelchair manual accessibility")
    ("🦼" "motorized wheelchair" "U+1F9BC" "transport wheelchair motorized accessibility")
    ("🛺" "auto rickshaw" "U+1F6FA" "transport rickshaw auto taxi asia")
    ("🚲" "bicycle" "U+1F6B2" "transport bicycle bike exercise eco")
    ("🛴" "kick scooter" "U+1F6F4" "transport scooter kick urban")
    ("🛹" "skateboard" "U+1F6F9" "sport skateboard skate urban")
    ("🛼" "roller skate" "U+1F6FC" "sport roller skate exercise")
    ("🚏" "bus stop" "U+1F68F" "place bus stop transport public")
    ("🛣️" "motorway" "U+1F6E3" "place motorway highway road")
    ("🛤️" "railway track" "U+1F6E4" "place railway track transport")
    ("🛢️" "oil drum" "U+1F6E2" "object oil drum barrel industrial")
    ("⛽" "fuel pump" "U+26FD" "place fuel pump gas station")
    ("🚨" "police car light" "U+1F6A8" "object police light emergency siren")
    ("🚥" "horizontal traffic light" "U+1F6A5" "object traffic light signal road")
    ("🚦" "vertical traffic light" "U+1F6A6" "object traffic light signal road")
    ("🛑" "stop sign" "U+1F6D1" "object stop sign traffic road")
    ("🚧" "construction" "U+1F6A7" "object construction barrier road work")

    ;; Objects
    ("⚓" "anchor" "U+2693" "object anchor ship sea boat")
    ("⛵" "sailboat" "U+26F5" "transport sailboat boat sea wind")
    ("🛶" "canoe" "U+1F6F6" "transport canoe boat water paddle")
    ("🚤" "speedboat" "U+1F6A4" "transport speedboat boat fast water")
    ("🛳️" "passenger ship" "U+1F6F3" "transport ship passenger cruise ferry")
    ("⛴️" "ferry" "U+26F4" "transport ferry ship water passenger")
    ("🛥️" "motor boat" "U+1F6E5" "transport boat motor engine water")
    ("🚢" "ship" "U+1F6A2" "transport ship cargo sea ocean")
    ("✈️" "airplane" "U+2708" "transport airplane flight aviation sky")
    ("🛩️" "small airplane" "U+1F6E9" "transport airplane small private")
    ("🛫" "airplane departure" "U+1F6EB" "transport airplane departure airport")
    ("🛬" "airplane arrival" "U+1F6EC" "transport airplane arrival airport")
    ("🪂" "parachute" "U+1FA82" "object parachute sky jump safety")
    ("💺" "seat" "U+1F4BA" "object seat airplane chair travel")
    ("🚁" "helicopter" "U+1F681" "transport helicopter flight aviation")
    ("🚟" "suspension railway" "U+1F69F" "transport railway suspension overhead")
    ("🚠" "mountain cableway" "U+1F6A0" "transport cableway mountain ski gondola")
    ("🚡" "aerial tramway" "U+1F6A1" "transport tramway aerial cable mountain")
    ("🛰️" "satellite" "U+1F6F0" "object satellite space communication orbit")
    ("🚀" "rocket" "U+1F680" "transport rocket space launch space")
    ("🛸" "flying saucer" "U+1F6F8" "object ufo flying saucer alien space")
    ("🛎️" "bellhop bell" "U+1F6CE" "object bell hotel service")
    ("🧳" "luggage" "U+1F9F3" "object luggage travel suitcase bag")
    ("⌛" "hourglass done" "U+231B" "object hourglass time sand done")
    ("⏳" "hourglass not done" "U+23F3" "object hourglass time sand flowing")
    ("⌚" "watch" "U+231A" "object watch time clock wrist")
    ("⏰" "alarm clock" "U+23F0" "object clock alarm time wake")
    ("⏱️" "stopwatch" "U+23F1" "object stopwatch time sport timer")
    ("⏲️" "timer clock" "U+23F2" "object timer clock time countdown")
    ("🕰️" "mantelpiece clock" "U+1F570" "object clock time antique mantel")
    ("🕛" "twelve o'clock" "U+1F55B" "time clock twelve midnight noon")
    ("🕧" "twelve-thirty" "U+1F567" "time clock twelve-thirty 12:30")
    ("🕐" "one o'clock" "U+1F550" "time clock one 1:00")
    ("🕜" "one-thirty" "U+1F55C" "time clock one-thirty 1:30")
    ("🕑" "two o'clock" "U+1F551" "time clock two 2:00")
    ("🕝" "two-thirty" "U+1F55D" "time clock two-thirty 2:30")
    ("🕒" "three o'clock" "U+1F552" "time clock three 3:00")
    ("🕞" "three-thirty" "U+1F55E" "time clock three-thirty 3:30")
    ("🕓" "four o'clock" "U+1F553" "time clock four 4:00")
    ("🕟" "four-thirty" "U+1F55F" "time clock four-thirty 4:30")
    ("🕔" "five o'clock" "U+1F554" "time clock five 5:00")
    ("🕠" "five-thirty" "U+1F560" "time clock five-thirty 5:30")
    ("🕕" "six o'clock" "U+1F555" "time clock six 6:00")
    ("🕡" "six-thirty" "U+1F561" "time clock six-thirty 6:30")
    ("🕖" "seven o'clock" "U+1F556" "time clock seven 7:00")
    ("🕢" "seven-thirty" "U+1F562" "time clock seven-thirty 7:30")
    ("🕗" "eight o'clock" "U+1F557" "time clock eight 8:00")
    ("🕣" "eight-thirty" "U+1F563" "time clock eight-thirty 8:30")
    ("🕘" "nine o'clock" "U+1F558" "time clock nine 9:00")
    ("🕤" "nine-thirty" "U+1F564" "time clock nine-thirty 9:30")
    ("🕙" "ten o'clock" "U+1F559" "time clock ten 10:00")
    ("🕥" "ten-thirty" "U+1F565" "time clock ten-thirty 10:30")
    ("🕚" "eleven o'clock" "U+1F55A" "time clock eleven 11:00")
    ("🕦" "eleven-thirty" "U+1F566" "time clock eleven-thirty 11:30")
    ("🌑" "new moon" "U+1F311" "astronomy moon new phase dark")
    ("🌒" "waxing crescent moon" "U+1F312" "astronomy moon crescent waxing phase")
    ("🌓" "first quarter moon" "U+1F313" "astronomy moon quarter first phase half")
    ("🌔" "waxing gibbous moon" "U+1F314" "astronomy moon gibbous waxing phase")
    ("🌕" "full moon" "U+1F315" "astronomy moon full phase bright")
    ("🌖" "waning gibbous moon" "U+1F316" "astronomy moon gibbous waning phase")
    ("🌗" "last quarter moon" "U+1F317" "astronomy moon quarter last phase half")
    ("🌘" "waning crescent moon" "U+1F318" "astronomy moon crescent waning phase")
    ("🌙" "crescent moon" "U+1F319" "astronomy moon crescent night sleep")
    ("🌚" "new moon face" "U+1F31A" "astronomy moon face new dark")
    ("🌛" "first quarter moon face" "U+1F31B" "astronomy moon face quarter first")
    ("🌜" "last quarter moon face" "U+1F31C" "astronomy moon face quarter last")
    ("🌡️" "thermometer" "U+1F321" "object thermometer temperature weather hot cold")
    ("☀️" "sun" "U+2600" "astronomy sun bright warm day")
    ("🌝" "full moon face" "U+1F31D" "astronomy moon face full bright")
    ("🌞" "sun with face" "U+1F31E" "astronomy sun face bright happy")
    ("🪐" "ringed planet" "U+1FA90" "astronomy planet ring saturn space")
    ("⭐" "star" "U+2B50" "astronomy star bright shiny night")
    ("🌟" "glowing star" "U+1F31F" "astronomy star glowing bright shiny")
    ("🌠" "shooting star" "U+1F320" "astronomy star shooting meteor wish")
    ("🌌" "milky way" "U+1F30C" "astronomy milky way galaxy space stars")
    ("☁️" "cloud" "U+2601" "weather cloud sky fluffy white")
    ("⛅" "cloud behind sun" "U+26C5" "weather cloud sun partly cloudy")
    ("⛈️" "cloud with lightning and rain" "U+26C8" "weather storm lightning rain thunder")
    ("🌤️" "sun behind small cloud" "U+1F324" "weather sun cloud partly cloudy")
    ("🌥️" "sun behind large cloud" "U+1F325" "weather sun cloud mostly cloudy")
    ("🌦️" "sun behind rain cloud" "U+1F326" "weather sun rain cloud sunshower")
    ("🌧️" "cloud with rain" "U+1F327" "weather rain cloud storm wet")
    ("🌨️" "cloud with snow" "U+1F328" "weather snow cloud cold winter")
    ("🌩️" "cloud with lightning" "U+1F329" "weather lightning storm electric thunder")
    ("🌪️" "tornado" "U+1F32A" "weather tornado storm wind dangerous")
    ("🌫️" "fog" "U+1F32B" "weather fog mist cloudy visibility")
    ("🌬️" "wind face" "U+1F32C" "weather wind face blow air")
    ("🌀" "cyclone" "U+1F300" "weather cyclone hurricane storm spiral")
    ("🌈" "rainbow" "U+1F308" "weather rainbow colorful rain sun")
    ("🌂" "closed umbrella" "U+1F302" "object umbrella closed rain weather")
    ("☂️" "umbrella" "U+2602" "object umbrella rain weather protection")
    ("☔" "umbrella with rain drops" "U+2614" "object umbrella rain weather wet")
    ("⛱️" "umbrella on ground" "U+26F1" "object umbrella beach ground vacation")
    ("⚡" "high voltage" "U+26A1" "object lightning electricity energy danger")
    ("❄️" "snowflake" "U+2744" "weather snowflake cold winter ice")
    ("☃️" "snowman" "U+2603" "weather snowman winter cold frosty")
    ("⛄" "snowman without snow" "U+26C4" "weather snowman winter cold")
    ("☄️" "comet" "U+2604" "astronomy comet space tail meteor")
    ("🔥" "fire" "U+1F525" "object fire hot flame burn")
    ("💧" "droplet" "U+1F4A7" "object water droplet liquid wet")
    ("🌊" "water wave" "U+1F30A" "object water wave ocean sea")

    ;; Symbols
    ("🎃" "jack-o-lantern" "U+1F383" "holiday halloween pumpkin jack lantern")
    ("🎄" "christmas tree" "U+1F384" "holiday christmas tree decoration festive")
    ("🎆" "fireworks" "U+1F386" "celebration fireworks festive party")
    ("🎇" "sparkler" "U+1F387" "celebration sparkler festive fire")
    ("🧨" "firecracker" "U+1F9E8" "celebration firecracker explosive festive")
    ("✨" "sparkles" "U+2728" "object sparkles shiny magical glitter")
    ("🎈" "balloon" "U+1F388" "celebration balloon party festive")
    ("🎉" "party popper" "U+1F389" "celebration party popper festive confetti")
    ("🎊" "confetti ball" "U+1F38A" "celebration confetti party festive")
    ("🎋" "tanabata tree" "U+1F38B" "holiday tanabata tree japanese festival")
    ("🎍" "pine decoration" "U+1F38D" "holiday pine decoration japanese new year")
    ("🎎" "japanese dolls" "U+1F38E" "holiday japanese dolls traditional culture")
    ("🎏" "carp streamer" "U+1F38F" "holiday carp streamer japanese children")
    ("🎐" "wind chime" "U+1F390" "object wind chime bell peaceful")
    ("🎑" "moon viewing ceremony" "U+1F391" "holiday moon viewing ceremony japanese")
    ("🧧" "red envelope" "U+1F9E7" "holiday red envelope chinese money gift")
    ("🎀" "ribbon" "U+1F380" "object ribbon decoration gift bow")
    ("🎁" "wrapped gift" "U+1F381" "object gift wrapped present birthday")
    ("🎗️" "reminder ribbon" "U+1F397" "object ribbon reminder awareness support")
    ("🎟️" "admission tickets" "U+1F39F" "object tickets admission event cinema")
    ("🎫" "ticket" "U+1F3AB" "object ticket event concert travel")
    ("🎖️" "military medal" "U+1F396" "object medal military honor award")
    ("🏆" "trophy" "U+1F3C6" "object trophy award winner victory")
    ("🏅" "sports medal" "U+1F3C5" "object medal sports award achievement")
    ("🥇" "1st place medal" "U+1F947" "object medal first place gold winner")
    ("🥈" "2nd place medal" "U+1F948" "object medal second place silver")
    ("🥉" "3rd place medal" "U+1F949" "object medal third place bronze")
    ("⚽" "soccer ball" "U+26BD" "sport soccer ball football game")
    ("⚾" "baseball" "U+26BE" "sport baseball ball game america")
    ("🥎" "softball" "U+1F94E" "sport softball ball game")
    ("🏀" "basketball" "U+1F3C0" "sport basketball ball hoop game")
    ("🏐" "volleyball" "U+1F3D0" "sport volleyball ball net game")
    ("🏈" "american football" "U+1F3C8" "sport football american ball game")
    ("🏉" "rugby football" "U+1F3C9" "sport rugby ball game")
    ("🎾" "tennis" "U+1F3BE" "sport tennis ball racket game")
    ("🥏" "flying disc" "U+1F94F" "sport frisbee disc flying game")
    ("🎳" "bowling" "U+1F3B3" "sport bowling ball pins game")
    ("🏏" "cricket game" "U+1F3CF" "sport cricket ball bat game")
    ("🏑" "field hockey" "U+1F3D1" "sport hockey field ball stick game")
    ("🏒" "ice hockey" "U+1F3D2" "sport hockey ice puck stick game")
    ("🥍" "lacrosse" "U+1F94D" "sport lacrosse stick ball game")
    ("🏓" "ping pong" "U+1F3D3" "sport ping pong table tennis paddle")
    ("🏸" "badminton" "U+1F3F8" "sport badminton shuttlecock racket")
    ("🥊" "boxing glove" "U+1F94A" "sport boxing glove fight punch")
    ("🥋" "martial arts uniform" "U+1F94B" "sport martial arts karate uniform")
    ("🥅" "goal net" "U+1F945" "sport goal net soccer hockey")
    ("⛳" "flag in hole" "U+26F3" "sport golf flag hole putting")
    ("⛸️" "ice skate" "U+26F8" "sport ice skate skating rink")
    ("🥌" "curling stone" "U+1F94C" "sport curling stone ice game")
    ("🎣" "fishing pole" "U+1F3A3" "sport fishing pole hook fish")
    ("🤿" "diving mask" "U+1F93F" "sport diving mask snorkel underwater")
    ("🎽" "running shirt" "U+1F3BD" "sport running shirt jersey athletic")
    ("🎿" "skis" "U+1F3BF" "sport ski skiing snow winter")
    ("🛷" "sled" "U+1F6F7" "sport sled snow winter downhill")
    ("🥇" "1st place medal" "U+1F947" "object medal first place gold winner")
    ("🥈" "2nd place medal" "U+1F948" "object medal second place silver")
    ("🥉" "3rd place medal" "U+1F949" "object medal third place bronze")
    ("🎖️" "military medal" "U+1F396" "object medal military honor award")
    ("🏆" "trophy" "U+1F3C6" "object trophy award winner victory")
    ("🏅" "sports medal" "U+1F3C5" "object medal sports award achievement")
    ("🎗️" "reminder ribbon" "U+1F397" "object ribbon reminder awareness support")
    ("🏵️" "rosette" "U+1F3F5" "object rosette decoration flower award")
    ("🎫" "ticket" "U+1F3AB" "object ticket event concert travel")
    ("🎟️" "admission tickets" "U+1F39F" "object tickets admission event cinema")
    ("🎪" "circus tent" "U+1F3AA" "place circus tent entertainment show")
    ("🎭" "performing arts" "U+1F3AD" "art theater performing arts drama masks")
    ("🎨" "artist palette" "U+1F3A8" "art palette paint colors creative")
    ("🎬" "clapper board" "U+1F3AC" "art film movie clapper board cinema")
    ("🎤" "microphone" "U+1F3A4" "object microphone sing music voice")
    ("🎧" "headphone" "U+1F3A7" "object headphone music audio sound")
    ("🎼" "musical score" "U+1F3BC" "art music score notes sheet")
    ("🎹" "musical keyboard" "U+1F3B9" "art music keyboard piano instrument")
    ("🥁" "drum" "U+1F941" "art music drum percussion instrument")
    ("🎷" "saxophone" "U+1F3B7" "art music saxophone jazz instrument")
    ("🎺" "trumpet" "U+1F3BA" "art music trumpet brass instrument")
    ("🎸" "guitar" "U+1F3B8" "art music guitar string instrument")
    ("🪕" "banjo" "U+1FA95" "art music banjo folk instrument")
    ("🎻" "violin" "U+1F3BB" "art music violin string classical")
    ("🎲" "game die" "U+1F3B2" "game dice die random chance")
    ("♟️" "chess pawn" "U+265F" "game chess pawn board strategy")
    ("🎯" "direct hit" "U+1F3AF" "game target dart hit bullseye")
    ("🎳" "bowling" "U+1F3B3" "sport bowling ball pins game")
    ("🎮" "video game" "U+1F3AE" "game video game controller play")
    ("🎰" "slot machine" "U+1F3B0" "game slot machine casino gambling")
    ("🧩" "puzzle piece" "U+1F9E9" "game puzzle piece jigsaw solve")

    ;; Hearts & Symbols
    ("❤️" "red heart" "U+2764" "emotion love heart red romantic")
    ("🧡" "orange heart" "U+1F9E1" "emotion love heart orange friendship")
    ("💛" "yellow heart" "U+1F49B" "emotion love heart yellow friendship")
    ("💚" "green heart" "U+1F49A" "emotion love heart green nature")
    ("💙" "blue heart" "U+1F499" "emotion love heart blue trust")
    ("💜" "purple heart" "U+1F49C" "emotion love heart purple luxury")
    ("🖤" "black heart" "U+1F5A4" "emotion love heart black dark")
    ("🤍" "white heart" "U+1F90D" "emotion love heart white pure")
    ("🤎" "brown heart" "U+1F90E" "emotion love heart brown earth")
    ("💔" "broken heart" "U+1F494" "emotion heart broken sad breakup")
    ("❣️" "exclamation heart" "U+2763" "emotion heart exclamation love")
    ("💕" "two hearts" "U+1F495" "emotion love hearts couple romantic")
    ("💞" "revolving hearts" "U+1F491" "emotion love hearts romantic spinning")
    ("💓" "beating heart" "U+1F493" "emotion heart beating pulse love")
    ("💗" "growing heart" "U+1F497" "emotion heart growing love increase")
    ("💖" "sparkling heart" "U+1F496" "emotion heart sparkling shiny love")
    ("💘" "cupid" "U+1F498" "emotion love cupid arrow romantic")
    ("💝" "gift heart" "U+1F49D" "emotion love heart gift ribbon")
    ("❤️‍🔥" "heart on fire" "U+2764" "emotion love heart fire passionate")
    ("❤️‍🩹" "mending heart" "U+2764" "emotion love heart healing mending")
    ("❤️‍👩‍👦" "family heart" "U+2764" "emotion love heart family mother son")
    ("❤️‍👩‍👧" "family heart" "U+2764" "emotion love heart family mother daughter")
    ("❤️‍👨‍👦" "family heart" "U+2764" "emotion love heart family father son")
    ("❤️‍👨‍👧" "family heart" "U+2764" "emotion love heart family father daughter")
    ("❤️‍👩‍👧‍👦" "family heart" "U+2764" "emotion love heart family mother children")
    ("❤️‍👨‍👧‍👦" "family heart" "U+2764" "emotion love heart family father children")
    ("❤️‍👩‍👦‍👦" "family heart" "U+2764" "emotion love heart family mother sons")
    ("❤️‍👨‍👦‍👦" "family heart" "U+2764" "emotion love heart family father sons")
    ("❤️‍👩‍👧‍👧" "family heart" "U+2764" "emotion love heart family mother daughters")
    ("❤️‍👨‍👧‍👧" "family heart" "U+2764" "emotion love heart family father daughters")
    ("💋" "kiss mark" "U+1F48B" "emotion kiss lips mark love")
    ("💌" "love letter" "U+1F48C" "emotion love letter message romantic")
    ("💘" "cupid" "U+1F498" "emotion love cupid arrow romantic")
    ("💝" "gift heart" "U+1F49D" "emotion love heart gift ribbon")
    ("💖" "sparkling heart" "U+1F496" "emotion heart sparkling shiny love")
    ("💗" "growing heart" "U+1F497" "emotion heart growing love increase")
    ("💓" "beating heart" "U+1F493" "emotion heart beating pulse love")
    ("💞" "revolving hearts" "U+1F491" "emotion love hearts romantic spinning")
    ("💕" "two hearts" "U+1F495" "emotion love hearts couple romantic")
    ("💟" "heart decoration" "U+1F49F" "emotion heart decoration pattern")
    ("❣️" "exclamation heart" "U+2763" "emotion heart exclamation love")
    ("💔" "broken heart" "U+1F494" "emotion heart broken sad breakup")
    ("❤️" "red heart" "U+2764" "emotion love heart red romantic")
    ("🧡" "orange heart" "U+1F9E1" "emotion love heart orange friendship")
    ("💛" "yellow heart" "U+1F49B" "emotion love heart yellow friendship")
    ("💚" "green heart" "U+1F49A" "emotion love heart green nature")
    ("💙" "blue heart" "U+1F499" "emotion love heart blue trust")
    ("💜" "purple heart" "U+1F49C" "emotion love heart purple luxury")
    ("🖤" "black heart" "U+1F5A4" "emotion love heart black dark")
    ("🤍" "white heart" "U+1F90D" "emotion love heart white pure")
    ("🤎" "brown heart" "U+1F90E" "emotion love heart brown earth")
    ("💯" "hundred points" "U+1F4AF" "symbol hundred points 100 perfect")
    ("💢" "anger symbol" "U+1F4A2" "emotion anger symbol vein mad")
    ("💥" "collision" "U+1F4A5" "object collision explosion boom impact")
    ("💫" "dizzy" "U+1F4AB" "emotion dizzy star spiral confused")
    ("💦" "sweat droplets" "U+1F4A6" "object sweat droplets water exercise")
    ("💨" "dashing away" "U+1F4A8" "object dash wind speed away")
    ("🕳️" "hole" "U+1F573" "object hole empty void black")
    ("💣" "bomb" "U+1F4A3" "object bomb explosion danger")
    ("💬" "speech balloon" "U+1F4AC" "object speech balloon chat message")
    ("👁️‍🗨️" "eye in speech bubble" "U+1F441" "object eye speech bubble see say")
    ("🗨️" "left speech bubble" "U+1F5E8" "object speech bubble chat message")
    ("🗯️" "right anger bubble" "U+1F5EF" "object anger bubble shout loud")
    ("💭" "thought balloon" "U+1F4AD" "object thought balloon think bubble")
    ("💤" "zzz" "U+1F4A4" "object zzz sleep tired night"))
  "List of emoji with their names, Unicode codepoints, and descriptive tags.")

;;;###autoload
(defun cc/consult-emoji ()
  "Select and insert an emoji using consult completion.
Shows emoji with their names and hexadecimal codepoints, with filtering."
  (interactive)
  (let ((candidates (cc/consult--emoji-candidates)))
    (insert (consult--read
             candidates
             :prompt "Emoji: "
             :category 'emoji
             :require-match t
             :lookup #'consult--lookup-cdr
             :sort nil
             :add-history (thing-at-point 'symbol)
             :history 'cc/consult--emoji-history
             :annotate #'cc/consult--emoji-annotate))))

(defun cc/consult--emoji-candidates ()
  "Generate list of emoji candidates with names and codepoints."
  (mapcar (lambda (emoji-data)
            (let* ((emoji-char (car emoji-data))
                   (name (cadr emoji-data))
                   (hex (caddr emoji-data))
                   (tags (cadddr emoji-data))
                   (display-str
                    (format "%-2s %-40s %-8s %s"
                            emoji-char
                            name
                            hex
                            (propertize tags 'face 'font-lock-comment-face))))
              (cons display-str emoji-char)))
          cc/consult--emoji-list))

(defun cc/consult--emoji-annotate (candidate)
  "Annotate emoji CANDIDATE with additional information."
  (let ((hex (get-text-property 0 'cc/consult--emoji-hex candidate)))
    (when hex
      (concat " " (propertize hex 'face 'font-lock-comment-face)))))

;; History variable for emoji selection
(defvar cc/consult--emoji-history nil)

(provide 'cc-consult-emoji)

;; Local Variables:
;; coding: utf-8
;; End:
;;; cc-consult-emoji.el ends here
